### ISSUE TITLE
Git Bash Instantly closes on startup.

### ISSUE THREAD

**Issue by ghost** [msysgit/git#310] opened 2015-02-03 10:18 UTC
Hello! Whenever I try and right click in a folder and click run git bash here it opens for a split second and closes. I think this may be because I am running windows 10 technical preview. I have tried running it in compatibility mode & admin mode and to no success. Would be great for this to be fixed.

**Comment by dscho** [comment] 2015-02-03 15:09
Unfortunately, this is [not a good bug report](https://github.com/msysgit/msysgit/wiki#issue-reporting-guidelines).

However, you can probably find out more detailed information what is going wrong (and consequently, you will have a better chance to fix the issue yourself) by ensuring that `Git Bash` from the Start Menu works, and then work up your way to the root cause by inserting logging statements as described [here](https://github.com/msysgit/msysgit/wiki/Diagnosing-why-Git-is-so-slow#redirecting-output-to-a-file).

**Comment by Puddanator** [comment] 2015-02-05 09:34
Actually it is a real issue because I CANNOT RUN GIT. I have looked up this issue everywhere I have tried several things to fix this. NOTHING WORKS! Oh but wait. When I rolled back to windows 7. Works fine. I wonder why?

**Comment by sschuberth** [comment] 2015-02-05 20:18
Maybe because you are running Windows 10 technical *preview*? ;-) More seriously, please don't expect us to fix potential issue that a single user as *only* in conjunction with software of preview quality. I'm not precluding there's an issue in Git. I'm just saying that for me it makes little sense to look into this just now when Windows 10 is not even released.

**Comment by CalMlynarczyk** [comment] 2015-02-10 19:08
Try calling Git from another shell (ex. CMD, PowerShell). If it errors out due to some sort of memory allocation issue like the one reported in #307, then you will have to run one of the fixes provided for that issue.

I run into the same problem almost daily on my Windows machine. You can either restart your system and try again, or you can use the ```rebase``` command against _sh.exe_ as an admin to some random memory address to temporarily fix the problem.

**Comment by suburbanworrier** [comment] 2015-08-06 09:59
I had this on a Windows 8.1 machine. Git Bash would start and almost instantly close when called from the context menu. I uninstalled and reinstalled with the simple (non cheetah) context menu option and all is now well.
HTH

**Comment by dscho** [comment] 2015-08-06 10:08
This issue unfortunately lacks enough information to do anything about it. It *might* be the famous DLL address problem (which would be addressed by [Git for Windows 2.x](https://git-for-windows.github.io/) anyway, which is intended to supersede msysgit-based Git for Windows 1.x).

So I am closing this issue, asking everybody who experiences this issue to try Git for Windows 2.x instead.

**Closed by dscho** 2015-08-06 10:08 UTC
