### ISSUE TITLE
I got sh.exe /dev/null error from fresh install Git Scm 

### ISSUE THREAD

**Issue by brucieshero** [msysgit/git#278] opened 2014-11-13 07:46 UTC
Just install git-1.9.4 on Window 7 64-bit 

when open git bash for the first time, it prompts

sh.exe": /dev/null: No such file or directory

when type any command, it also prompts

sh.exe": command: command not found
sh.exe": /dev/null: No such file or directory

I've google for the solution for sometime and I found no solution for me as a newbie

**Comment by dscho** [comment] 2015-08-25 09:53
Closing here because Git for Windows 1.x is now obsolete. Please try again with [Git for Windows 2.x](http://git-for-windows.github.io/) and if the problem persists, please [open a new ticket with enough information to help others reproduce the problem](http://git-for-windows.github.io/#contribute).

**Closed by dscho** 2015-08-25 09:53 UTC
