### ISSUE TITLE
Redirect to Git for Windows 2.x

### ISSUE THREAD

**Issue by techtonik** [msysgit/git#356] opened 2015-06-04 19:05 UTC
If this project is phased out, maybe it is worth to rename it to msysGit 1.9.5 and place a redirection to the new site? http://git-for-windows.github.io/ It could save me a few months of waiting for 2.x.

**Comment by linquize** [comment] 2015-06-05 00:53
git 2.x release is still called rc version

**Comment by techtonik** [comment] 2015-06-05 06:40
I c.

**Comment by FallenGameR** [comment] 2015-07-28 21:34
Why 2.x is RC?
Release notes https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.5.0.txt don't mention that. Looks like a stable release.

**Comment by nelson6e65** [comment] 2015-07-29 01:46
Check the latest pre-release in https://github.com/git-for-windows/git/releases:
[v2.4.6.windows.1](https://github.com/git-for-windows/git/tree/v2.4.6.windows.1) Fifth **release candidate** of Git for Windows

**Comment by YueLinHo** [comment] 2015-07-29 01:48
ATM, the latest git is 2.5.0, see [here](https://git-scm.com/).
There is a link for GfW in that page, and it links to 1.9.5. See [here](https://git-scm.com/download/win).
Also see the [Gfw Main page](https://msysgit.github.io/) (also 1.9.5).
So, latest release is 1.9.5.

There are some **Developer's Preview Releases**(for dev test) and **Release candidates**(for user test).

The first developer's preview release is [v2.3.4.windows.2](https://github.com/git-for-windows/git/releases/tag/v2.3.4.windows.2)? (2015-03-26)
It mentioned: 
*This is the developers' preview to show what Git for Windows 2.x looks like. Please note that it is not intended for use in production.*

Latest developer's preview release is [2.3.5.windows.7](https://github.com/git-for-windows/git/releases/tag/v2.3.5.windows.7) (2015-04-10)

The first release candidate is [2.4.2.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.4.2.windows.1) (2015-05-28)

ATM, the latest release candidate is [2.4.6.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.4.6.windows.1) (2015-07-18)

I guess 2.5.0.windows.1 is coming.
(Release list is [here](https://github.com/git-for-windows/git/releases))

>Why 2.x is RC?

Well, lots people ask this question, it's a big one.
I don't think I can answer this question.
But I see the change mentioned above, and believe the GfW is getting stable.

**Comment by linquize** [comment] 2015-07-29 11:02
For 2.5.0, @dscho has to solve the compilation problem, before 2.5.0 can be released.

**Comment by dscho** [comment] 2015-07-29 13:28
Yep, 2.5.0.windows.1 is coming. Indeed, I still need to address [this issue](https://github.com/git-for-windows/git/issues/257) first, but there is also [this issue](https://github.com/git-for-windows/git/issues/193). In general, if you want to know what is missing for a final release, it is a good idea to look at [the milestone](https://github.com/git-for-windows/git/milestones/First%20release%20of%20Git%20for%20Windows%20generated%20using%20the%20new%20SDK).

**Comment by FallenGameR** [comment] 2015-07-29 17:51
YueLinHo, thanks for explanation!
dscho, thanks for making 2.5 possible!
You guys rock. I will patiently wait for the new release =)

**Comment by YueLinHo** [comment] 2015-07-30 11:34
@FallenGameR Yor're welcome. And think you for reading my long long comment. ^_^

**Comment by dscho** [comment] 2015-08-18 20:50
This ticket is actually a duplicate of part of https://github.com/git-for-windows/git/issues/12 which I just closed.

**Closed by dscho** 2015-08-18 20:50 UTC
