### ISSUE TITLE
git add --interactive fails on subdir

### ISSUE THREAD

**Issue by albfan** [msysgit/git#182] opened 2014-05-14 16:04 UTC
Filtering on a path, to add interactively only files from subdir

```bash-prompt
> cd subdir
> git add -i .
Can't exec "git": Bad file number at C:\Program Files (x86)\Git/libexec/git-core\git-add--interactive line 180.
Died at C:\Program Files (x86)\Git/libexec/git-core\git-add--interactive line 180.
```

it is a perl script. I checked I'm using perl from msysgit installation. 

```shell
>perl
"perl" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

>"\Program Files (x86)\Git\bin\perl.exe" --version

This is perl, v5.8.8 built for msys
```

My version of git is the latest 1.9.2

```shell
>git --version
git version 1.9.2.msysgit.0
```

**Comment by kkheller** [comment] 2015-05-27 01:36
For anyone still interested on this thread, I just posted "a patch for a patch" (a new update to @PhilipDavis's August 2014 work).  You can see it here: https://github.com/msysgit/git/pull/218#issuecomment-105707273

Now "git add -p SOME_DIR" works for me 100% of the time again, no matter whether the SOME_DIR subfolder contains a dozen files or several hundred. (using today's patch)

I searched my error on google many times and never found this thread.  In the future I will know to come straight to github and search the issues here.  However, for the sake of others, I will post my error here in the hopes that it will help somebody else find their way to this issue tracker:

```
$ git add -p LargeFolder/
Can't exec "git": Bad file number at C:\msysgit\msysgit/libexec/git-core\git-add--interactive line 180.
Died at C:\msysgit\msysgit/libexec/git-core\git-add--interactive line 180.
```

(Other search terms for the SEO of this page: folder, subdirectory, directory, git add --patch pathspec, microsoft windows 7, win32, msys, bash, options)

(i was always searching with "git add -p". it seems that only @juliankrispel mentioned that exact invocation on https://github.com/msysgit/msysgit/issues/203)

Notes about reproducing this:

git add -p SmallFolder/  # succeeds
git add -p FOLDER_WITH_HUGE_CONTENT/ # fails

In my case, here are the statistics for my FOLDER_WITH_HUGE_CONTENT:

```find FOLDER_WITH_HUGE_CONTENT/ | wc -l``` produces a line count of 505.

```find FOLDER_WITH_HUGE_CONTENT/ | wc -c``` produces a char count of 21734.

Anyway, i hope that others can take today's patch (https://github.com/msysgit/git/pull/218#issuecomment-105707273) and run it in their msysgit environment and experience the same relief from this issue as i have!

**Comment by dscho** [comment] 2015-08-22 15:55
This will be fixed in [Git for Windows 2.x](https://git-for-windows.github.io/) via https://github.com/git-for-windows/git/pull/305.

**Closed by dscho** 2015-08-22 15:55 UTC
